node {

    try{

    
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2'){
        stage('Build'){
            sh 'mvn -B -DskipTests clean package'
        }

        stage('Test'){
             sh 'mvn test'
        }
        stage('Manual Approval'){
                // sh './jenkins/scripts/deliver.sh'
                input message: 'Lanjutkan ke tahap Deploy? (Klik "Proceed" untuk Melanjutkan)'
            }
    }

    } catch (Exception e){
        currentBuild.result = 'FAILURE'
        throw e
    }finally{
        docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2'){
            junit 'target/surefire-reports/*.xml'
            stage('Deploy'){
                echo 'Holding instance for 1 minute.....'
                sleep(time: 1, unit: 'MINUTES')
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }

}
    

