node {

    try{

    
    docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2'){
        stage('Build'){
            sh 'mvn -B -DskipTests clean package'
        }

        stage('Test'){
             sh 'mvn test'
        }
        
    }

    } catch (Exception e){
        currentBuild.result = 'FAILURE'
        throw e
    }finally{
        docker.image('maven:3.9.0').inside('-v /root/.m2:/root/.m2'){
            junit 'target/surefire-reports/*.xml'
            stage('Deliver'){
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }

}
    

